### ISSUE TITLE
Unibuild -> Build Menu fucntion does not work if folder UniBuild/Editor not exist

### ISSUE THREAD

**Issue by takaaptech** [UniGameTeam/UniGame.UniBuild#3]
@Mefodei 
When I import and run the Unibuild -> Build Menu, we have this error
DirectoryNotFoundException: Could not find a part of the path "/UniBuild/Assets/UniGame.Generated/UniBuild/Editor/BuildMethods.cs".

If we create the folder UniBuild/Editor then the code auto-gen works.
Please check if we can auto-create folders if that folder not exist!

**Comment by Mefodei** [comment]
Hi @takaaptech
i will check that issue today

**Comment by Mefodei** [comment]
@takaaptech  I check that issue at local project and there is no any error with that. What version of package do you use?

**Comment by takaaptech** [comment]
@Mefodei latest version

I think I found the problem, UniBuild create a new folder inside the project but with an absolute path and the same path with the Assets folder

![image](https://user-images.githubusercontent.com/6276251/115105849-ac9a5c80-9f8b-11eb-9595-f6b3247e60e1.png)



![image](https://user-images.githubusercontent.com/6276251/115105823-7c52be00-9f8b-11eb-9b41-91fac214f808.png)


![image](https://user-images.githubusercontent.com/6276251/115105772-2a119d00-9f8b-11eb-9e4b-1868231b8850.png)

![image](https://user-images.githubusercontent.com/6276251/115105780-3ac21300-9f8b-11eb-809b-e7d76a1dc213.png)

**Comment by Mefodei** [comment]
Thx, i think the reason of that different target OS. I make all test on my Wnidows PC. But you try to test on OSX. I Will fix that

**Comment by Mefodei** [comment]
![image](https://user-images.githubusercontent.com/7457166/115157208-a80b9c00-a090-11eb-8e1f-479258cc794d.png)
@takaaptech  Try this new version

**Comment by takaaptech** [comment]
@Mefodei I try a new version but it is still generating new folder outsize Unity
![image](https://user-images.githubusercontent.com/6276251/115197602-59efaa80-a11b-11eb-9179-56489a52d74c.png)

**Comment by Mefodei** [comment]
@takaaptech  i will check on OSX environment

**Comment by Mefodei** [comment]
@takaaptech try to use new version
![image](https://user-images.githubusercontent.com/7457166/116444119-143e8a80-a85d-11eb-961a-c3d22ca95c3d.png)

@HartMagic fix that issue
